package at.shiftcontrol.lib.type;

public enum NotificationType {

    /* volunteer notifications */
    VOLUNTEER_REQUESTED_JOIN_ACCEPTED,      // POSITIONSLOT_REQUEST_JOIN_ACCEPTED
    VOLUNTEER_REQUESTED_JOIN_DECLINED,      // POSITIONSLOT_REQUEST_JOIN_DECLINED
    VOLUNTEER_REQUESTED_LEAVE_ACCEPTED,     // POSITIONSLOT_REQUEST_LEAVE_ACCEPTED
    VOLUNTEER_REQUESTED_LEAVE_DECLINED,     // POSITIONSLOT_REQUEST_LEAVE_DECLINED

    VOLUNTEER_AUCTION_CLAIMED,  // AUCTION_CLAIMED
    VOLUNTEER_TRADE_REQUESTED,  // TRADE_REQUEST_CREATED
    VOLUNTEER_TRADE_ACCEPTED,   // TRADE_REQUEST_COMPLETED
    VOLUNTEER_TRADE_DECLINED,   // TRADE_REQUEST_DECLINED

    VOLUNTEER_PLANS_ADDED,      // USERS_EVENT_BULK_ADD
    VOLUNTEER_PLANS_REMOVED,    // USERS_EVENT_BULK_REMOVE
    VOLUNTEER_PLANS_UPDATED,    // USERS_EVENT_UPDATE

    VOLUNTEER_ROLE_ASSIGNED,    // ROLE_ASSIGNED
    VOLUNTEER_ROLE_UNASSIGNED,  // ROLE_UNASSIGNED
    VOLUNTEER_ROLES_ADDED,      // USERS_PLAN_BULK_ADD
    VOLUNTEER_ROLES_REMOVED,    // USERS_PLAN_BULK_REMOVE
    VOLUNTEER_ROLES_UPDATED,    // USERS_PLAN_UPDATE

    VOLUNTEER_PLANS_LOCKED,     // USERS_EVENT_LOCK
    VOLUNTEER_PLANS_UNLOCKED,   // USERS_EVENT_UNLOCK
    VOLUNTEER_PLANS_RESET,      // USERS_RESET

    VOLUNTEER_AUTO_ASSIGNED,    //
    VOLUNTEER_SHIFT_REMINDER,   //


    /* planner notifications */
    PLANNER_VOLUNTEER_REQUESTED_JOIN,   // POSITIONSLOT_REQUEST_JOIN_CREATED
    PLANNER_VOLUNTEER_REQUESTED_LEAVE,  // POSITIONSLOT_REQUEST_LEAVE_CREATED
    PLANNER_VOLUNTEER_JOINED_PLAN,      // SHIFTPLAN_JOINED_VOLUNTEER


    /* admin notifications */
    ADMIN_PLANNER_JOINED_PLAN,      // SHIFTPLAN_JOINED_PLANNER
    ADMIN_TRUST_ALERT_RECEIVED,     // TRUST_ALERT_RECEIVED
    ADMIN_REWARD_SYNC_USED,         //
}
