package at.shiftcontrol.lib.type;

public enum NotificationType {

    /* volunteer notifications */
    VOLUNTEER_REQUEST_HANDLED,
    //  POSITIONSLOT_REQUEST_JOIN_ACCEPTED
    //  POSITIONSLOT_REQUEST_JOIN_DECLINED
    //  POSITIONSLOT_REQUEST_LEAVE_ACCEPTED
    //  POSITIONSLOT_REQUEST_LEAVE_DECLINED

    VOLUNTEER_TRADE_OR_AUCTION,
    // includes:
    //  AUCTION_CLAIMED
    //  TRADE_REQUEST_CREATED
    //  TRADE_REQUEST_COMPLETED
    //  TRADE_REQUEST_DECLINED

    VOLUNTEER_PLANS_CHANGED,
    // includes:
    //  USERS_EVENT_BULK_ADD
    //  USERS_EVENT_BULK_REMOVE
    //  USERS_EVENT_UPDATE

    VOLUNTEER_ROLES_CHANGED,
    // includes:
    //  ROLE_ASSIGNED
    //  ROLE_UNASSIGNED
    //  USERS_PLAN_BULK_ADD
    //  USERS_PLAN_BULK_REMOVE
    //  USERS_PLAN_UPDATE

    VOLUNTEER_STATUS_CHANGED,
    // includes:
    //  USERS_EVENT_LOCK
    //  USERS_EVENT_UNLOCK
    //  USERS_RESET

    VOLUNTEER_AUTO_ASSIGNED,
    VOLUNTEER_SHIFT_REMINDER,


    /* planner notifications */
    PLANNER_VOLUNTEER_REQUEST,
    // includes:
    //  POSITIONSLOT_REQUEST_JOIN_CREATED
    //  POSITIONSLOT_REQUEST_LEAVE_CREATED

    PLANNER_VOLUNTEER_JOINED_PLAN,
    // SHIFTPLAN_JOINED_VOLUNTEER


    /* admin notifications */
    ADMIN_PLANNER_JOINED_PLAN,
    // includes:
    //  SHIFTPLAN_JOINED_PLANNER

    ADMIN_TRUST_ALERT_RECEIVED,
    // includes:
    //  TRUST_ALERT_RECEIVED

    ADMIN_REWARD_SYNC_USED,
}
