trust:
  shiftservice:
    baseUrl: http://shiftservice:8080/
    endpoint: api/v1/trust-alerts
    apiKey:
  oauth2:
    client:
      tokenUrl: http://keycloak:8080/realms/dev/protocol/openid-connect/token
      clientId: internal
      clientSecret: 3mnwKdFacOw8DiTfcCHHSVVMiHjzIoms
      scope:
