package at.shiftcontrol.lib.event;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum EventType {
    ACTIVITY_CREATED(RoutingKeys.ACTIVITY_CREATED),
    ACTIVITY_UPDATED(RoutingKeys.ACTIVITY_UPDATED),
    ACTIVITY_DELETED(RoutingKeys.ACTIVITY_DELETED),

    AUCTION_CREATED(RoutingKeys.AUCTION_CREATED),
    AUCTION_CANCELED(RoutingKeys.AUCTION_CANCELED),
    AUCTION_CLAIMED(RoutingKeys.AUCTION_CLAIMED),

    TRADE_REQUEST_CREATED(RoutingKeys.TRADE_REQUEST_CREATED),
    TRADE_REQUEST_DECLINED(RoutingKeys.TRADE_REQUEST_DECLINED),
    TRADE_REQUEST_CANCELED(RoutingKeys.TRADE_REQUEST_CANCELED),
    TRADE_REQUEST_COMPLETED(RoutingKeys.TRADE_REQUEST_COMPLETED),

    EVENT_CREATED(RoutingKeys.EVENT_CREATED),
    EVENT_UPDATED(RoutingKeys.EVENT_UPDATED),
    EVENT_DELETED(RoutingKeys.EVENT_DELETED),
    EVENT_CLONED(RoutingKeys.EVENT_CLONED),
    EVENT_EXPORTED(RoutingKeys.EVENT_EXPORTED),
    EVENT_IMPORTED(RoutingKeys.EVENT_IMPORTED),

    SHIFTPLAN_LEAVE(RoutingKeys.SHIFTPLAN_LEAVE),

    LOCATION_CREATED(RoutingKeys.LOCATION_CREATED),
    LOCATION_UPDATED(RoutingKeys.LOCATION_UPDATED),
    LOCATION_DELETED(RoutingKeys.LOCATION_DELETED),

    VOLUNTEER_NOTIFICATION_PREFERENCE_UPDATED(RoutingKeys.VOLUNTEER_NOTIFICATION_PREFERENCE_UPDATED),
    PRETALX_API_KEY_INVALID(RoutingKeys.PRETALX_API_KEY_INVALID),
    TRUST_ALERT_RECEIVED(RoutingKeys.TRUST_ALERT_RECEIVED),

    REWARDPOINTS_SHARETOKEN_CREATED(RoutingKeys.REWARDPOINTS_SHARETOKEN_CREATED),
    REWARDPOINTS_TRANSACTION_CREATED(RoutingKeys.REWARDPOINTS_TRANSACTION_CREATED),
    REWARDPOINTS_TRANSACTION_FAILED(RoutingKeys.REWARDPOINTS_TRANSACTION_FAILED),

    POSITIONSLOT_CREATED(RoutingKeys.POSITIONSLOT_CREATED),
    POSITIONSLOT_UPDATED(RoutingKeys.POSITIONSLOT_UPDATED),
    POSITIONSLOT_DELETED(RoutingKeys.POSITIONSLOT_DELETED),
    POSITIONSLOT_JOINED(RoutingKeys.POSITIONSLOT_JOINED),
    POSITIONSLOT_LEFT(RoutingKeys.POSITIONSLOT_LEFT),
    POSITIONSLOT_REQUEST_JOIN(RoutingKeys.POSITIONSLOT_REQUEST_JOIN),
    POSITIONSLOT_REQUEST_JOIN_WITHDRAW(RoutingKeys.POSITIONSLOT_REQUEST_JOIN_WITHDRAW),
    POSITIONSLOT_REQUEST_JOIN_ACCEPTED(RoutingKeys.POSITIONSLOT_REQUEST_JOIN_ACCEPTED),
    POSITIONSLOT_REQUEST_JOIN_DECLINED(RoutingKeys.POSITIONSLOT_REQUEST_JOIN_DECLINED),
    POSITIONSLOT_REQUEST_LEAVE(RoutingKeys.POSITIONSLOT_REQUEST_LEAVE),
    POSITIONSLOT_REQUEST_LEAVE_ACCEPTED(RoutingKeys.POSITIONSLOT_REQUEST_LEAVE_ACCEPTED),
    POSITIONSLOT_REQUEST_LEAVE_DECLINED(RoutingKeys.POSITIONSLOT_REQUEST_LEAVE_DECLINED),
    POSITIONSLOT_REQUEST_LEAVE_WITHDRAW(RoutingKeys.POSITIONSLOT_REQUEST_LEAVE_WITHDRAW),
    POSITIONSLOT_PREFERENCE_UPDATED(RoutingKeys.POSITIONSLOT_PREFERENCE_UPDATED),

    ROLE_CREATED(RoutingKeys.ROLE_CREATED),
    ROLE_UPDATED(RoutingKeys.ROLE_UPDATED),
    ROLE_DELETED(RoutingKeys.ROLE_DELETED),
    ROLE_ASSIGNED(RoutingKeys.ROLE_ASSIGNED),
    ROLE_UNASSIGNED(RoutingKeys.ROLE_UNASSIGNED),

    SHIFT_CREATED(RoutingKeys.SHIFT_CREATED),
    SHIFT_UPDATED(RoutingKeys.SHIFT_UPDATED),
    SHIFT_DELETED(RoutingKeys.SHIFT_DELETED),

    SHIFTPLAN_CREATED(RoutingKeys.SHIFTPLAN_CREATED),
    SHIFTPLAN_UPDATED(RoutingKeys.SHIFTPLAN_UPDATED),
    SHIFTPLAN_DELETED(RoutingKeys.SHIFTPLAN_DELETED),
    SHIFTPLAN_LOCKSTATUS_CHANGED(RoutingKeys.SHIFTPLAN_LOCKSTATUS_CHANGED),
    SHIFTPLAN_INVITE_CREATED(RoutingKeys.SHIFTPLAN_INVITE_CREATED),
    SHIFTPLAN_INVITE_DELETED(RoutingKeys.SHIFTPLAN_INVITE_DELETED),
    SHIFTPLAN_INVITE_REVOKED(RoutingKeys.SHIFTPLAN_INVITE_REVOKED),
    SHIFTPLAN_JOINED_VOLUNTEER(RoutingKeys.SHIFTPLAN_JOINED_VOLUNTEER),
    SHIFTPLAN_JOINED_PLANNER(RoutingKeys.SHIFTPLAN_JOINED_PLANNER),

    TIMECONSTRAINT_CREATED(RoutingKeys.TIMECONSTRAINT_CREATED),
    TIMECONSTRAINT_DELETED(RoutingKeys.TIMECONSTRAINT_DELETED),

    USERS_EVENT_UPDATE(RoutingKeys.USERS_EVENT_UPDATE),
    USERS_EVENT_LOCK(RoutingKeys.USERS_EVENT_LOCK),
    USERS_EVENT_UNLOCK(RoutingKeys.USERS_EVENT_UNLOCK),
    USERS_RESET(RoutingKeys.USERS_RESET),
    USERS_PLAN_UPDATE(RoutingKeys.USERS_PLAN_UPDATE),
    USERS_EVENT_BULK_ADD(RoutingKeys.USERS_EVENT_BULK_ADD),
    USERS_EVENT_BULK_REMOVE(RoutingKeys.USERS_EVENT_BULK_REMOVE),
    USERS_PLAN_BULK_ADD(RoutingKeys.USERS_PLAN_BULK_ADD),
    USERS_PLAN_BULK_REMOVE(RoutingKeys.USERS_PLAN_BULK_REMOVE);

    private final String routingKey;
}
