name: Release

permissions:
  contents: write

on:
  push:
  pull_request:

jobs:
  test:
    name: Create Release with OpenAPI specs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build audit and shiftservice OpenAPI specs
        run: mvn --no-transfer-progress -B clean verify -Popenapi -DskipTests -pl shiftservice,auditlog -am

      - name: Prepare OpenAPI artifacts
        run: |
          cp shiftservice/target/openapi.json shiftservice-openapi.json
          cp auditlog/target/openapi.json auditlog-openapi.json


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.COMMIT_SHORT_SHA }}
          release_name: shiftcontrol-java-backend
          draft: false
          prerelease: false
      - name: Upload OpenAPI files
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: |
            shiftservice-openapi.json
            auditlog-openapi.json
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true